import {StyleSheet} from 'react-native';

export const SettingCSS = StyleSheet.create({
  container: {
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  header: {
    width: '100%',
    height: 56,
  },
  headerSetting: {
    height: 56,
    width: 360,
  },
  textBtn: {
    width: 123,
    height: 310,
  },
  lingua: {
    fontFamily: 'roboto-700',
    color: '#121212',
    height: 24,
    width: 57,
    fontSize: 15,
    marginLeft: 34,
  },
  materialButtonViolet3: {
    height: 52,
    width: 120,
    borderRadius: 15,
    marginTop: 19,
  },
  materialButtonViolet4: {
    height: 52,
    width: 120,
    borderRadius: 15,
    marginTop: 16,
  },
  materialButtonViolet5: {
    height: 52,
    width: 120,
    borderRadius: 15,
    marginTop: 20,
  },
  materialButtonViolet6: {
    height: 53,
    width: 120,
    borderRadius: 15,
    marginTop: 22,
  },
  footer: {
    width: '100%',
    height: 56,
  },
  footerSetting: {
    height: 56,
    width: 360,
  },
  container1: {
    height: '100%',
    backgroundColor: '#3F51B5',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 2,
    minWidth: 88,
    paddingLeft: 16,
    paddingRight: 16,
  },
  italiano: {
    color: '#fff',
    fontSize: 16,
  },
  container2: {
    height: '100%',
    backgroundColor: '#3F51B5',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 2,
    minWidth: 88,
    paddingLeft: 16,
    paddingRight: 16,
  },
  english: {
    color: '#fff',
    fontSize: 16,
  },
  container3: {
    height: '100%',
    backgroundColor: '#3F51B5',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 2,
    minWidth: 88,
    paddingLeft: 16,
    paddingRight: 16,
  },
  francais: {
    color: '#fff',
    fontSize: 16,
  },
  container4: {
    height: '100%',
    backgroundColor: '#3F51B5',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 2,
    minWidth: 88,
    paddingLeft: 16,
    paddingRight: 16,
  },
  deutsch: {
    color: '#fff',
    fontSize: 16,
  },
});
