import {StyleSheet} from 'react-native';

export const BluetoothCSS = StyleSheet.create({
  container: {
    flex: 1,
  },
  bluetoothSchermo: {
    width: 361,
    height: 736,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
  },
  header: {
    width: 360,
    height: 56,
  },
  headerBluetooth: {
    height: 56,
    width: 360,
  },
  btn: {
    width: 291,
    height: 137,
  },
  btnAttiva: {
    height: 55,
    width: 121,
    borderRadius: 15,
  },
  scan: {
    height: 55,
    width: 121,
    borderRadius: 15,
    marginLeft: 49,
  },
  btnAttivaRow: {
    height: 55,
    flexDirection: 'row',
  },
  btnDisattiva: {
    height: 55,
    width: 121,
    borderRadius: 15,
  },
  stopScan: {
    height: 55,
    width: 121,
    borderRadius: 15,
    marginLeft: 49,
  },
  btnDisattivaRow: {
    height: 55,
    flexDirection: 'row',
    marginTop: 26,
  },
  scrollView: {
    width: 291,
    height: 390,
  },
  scrollArea: {
    width: 291,
    height: 390,
    backgroundColor: 'rgba(230, 230, 230,1)',
  },
  scrollArea_contentContainerStyle: {
    height: 390,
    width: 291,
  },
  footer: {
    width: 361,
    height: 56,
  },
  footerBluetooth: {
    height: 56,
    width: 361,
  },
  container1: {
    backgroundColor: '#3F51B5',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 2,
    minWidth: 88,
    paddingLeft: 16,
    paddingRight: 16,
  },
  stopScan: {
    color: '#fff',
    fontSize: 14,
  },
  container2: {
    height: '100%',
    backgroundColor: '#3F51B5',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 2,
    minWidth: 88,
    paddingLeft: 16,
    paddingRight: 16,
  },
  scan: {
    color: '#fff',
    fontSize: 14,
  },
  scan1: {
    height: 55,
    width: 121,
    borderRadius: 15,
    marginLeft: 49,
  },
  container3: {
    backgroundColor: '#2196F3',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 2,
    minWidth: 88,
    paddingLeft: 16,
    paddingRight: 16,
  },
  disattiva: {
    color: '#fff',
    fontSize: 14,
  },
  container4: {
    backgroundColor: '#F44336',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 2,
    minWidth: 88,
    paddingLeft: 16,
    paddingRight: 16,
  },
  attiva: {
    color: '#fff',
    fontSize: 14,
  },
});
